config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


  devise_scope :user do
      get 'users/sign_out' =>'devise/sessions#destroy'
  authenticated :user do
    root 'chat#index', as: :authenticated_root
  end
  

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
  
  end
  
  

   get 'users/index' =>'users#index'
   get 'conversations/index' =>'conversations#index'

    resources :users do 
        

        resources :conversations

    end
    
    resources :conversations do 
        
        resources :messages
    end

  resources :chat


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :user, foreign_key: :user_id, class_name: 'User'
  belongs_to :receptor, foreign_key: :id_receptor, class_name: 'User'
  has_many :messages
  
  scope :between, -> (id_receptor, user_id) do
    where("(conversations.id_receptor = ? AND conversations.user_id = ?) OR (conversations.id_receptor = ? AND conversations.user_id = ?)", id_receptor, user_id, user_id, id_receptor)
    end


end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation,foreign_key: :conversation_id, class_name: 'Conversation'
  belongs_to :user, foreign_key: :sender, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :conversations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  
  protected

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:is_female, :date_of_birth,:trainer])
        devise_parameter_sanitizer.permit(:account_updates, keys: [:name,:is_female, :date_of_birth,:trainer])
    end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
    
    def index
        
        
    end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @users=User.all
    @conversations = Conversation.all
  end
  
  def show

    @conversation = Conversation.find(params[:id])
  end



  def create
      
    if Conversation.between(params[:id_receptor], params[:user_id]).present?
        @conversation = Conversation.between(params[:id_receptor], params[:user_id]).first
    else
      
    @conversation = Conversation.create(conversation_params)
    if @conversation.save
      flash[:success] = 'Chat created!'
    end
    end
    redirect_to conversation_path(@conversation)

  end

  private

  def conversation_params

    params.permit(:id_receptor,:user_id )

  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    
  def create
    @conversation = Conversation.find(params[:conversation_id])
    @message = @conversation.messages.create(message_param)
    @message.save
    
    redirect_to conversation_path(@conversation)
  end
  
  private
  def message_param
     #params.require(:post).permit(:title, :body)
     params.require(:message).permit(:content, :sender) 
  end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end
    def show
        @users = User.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chat/_navbar.html.erb
<html lang="en">
<head>

<title>Style</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
    <li><%= link_to 'ChatApp', conversations_index_path %></li>
      <li><%= link_to 'Messages', conversations_index_path %></li>
      <li><%= link_to 'Contacts', users_index_path %></li>
      <li><%= link_to 'Profile', edit_user_registration_path %></li>
      <li><%= link_to 'Sign Out', users_sign_out_path %></li>
     
    </ul>
  </div>
</nav>


</body>
</html>

app/views/chat/_test.html.erb
<h3>New Chat</h3>
<p>Select a user:</p>
    <% @users.each do |user| %>
      <% if user != current_user %>
        <%= user.name %>
        <%= user.email %>
      <% end %>
      <br>
<% end %>

app/views/chat/index.html.erb
  <p>probando un parrafo</p>

app/views/chat/show.html.erb
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body></body>
</html>

app/views/conversations/_conversation.html.erb
<html>
  <head>
    <title></title>
    <meta content="">
    <style></style>
  </head>
  <body></body>
</html>

app/views/conversations/index.html.erb
<head>
<style>


.chateo{
    margin-top: 40px;
    margin-left: 105px;
}

.lista{
    margin-left: 50px;
}


</style>
</head>



<div class="chateo">
    <h1>Chats</h1>
</div>

<% @conversations.each do |conversation| %>
<div class="lista">
    <% if conversation.user == current_user || conversation.receptor==current_user %>
        <% if conversation.user == current_user  %>
            <% other=conversation.receptor %>
        <% else %>
            <% other=conversation.user %>
        <% end %>
        <h2><%= link_to other.name, conversation %></h2>


        <%= other.email %>
    <% end %>
</div>
<% end %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="col-md-7 col-md-offset-2">
  <% if @conversation.user == current_user  %>
            <% other=@conversation.receptor %>
        <% else %>
            <% other=@conversation.user %>
        <% end %>
    <h3><%= other.name%></h3>

    <div>

      <%= render @conversation.messages %>
      
      <h6>New Message</h6>
      <%= render 'messages/form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <% if user_signed_in? %>
        <%=render 'chat/navbar' %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
<%= f.hidden_field :sender, value: current_user.id %>
  <div class="row">
    <div class="col-md-12">
      <div class="field">
        <%= f.text_area :content, class: "form-control" %>
      </div>
    </div>
  </div>
  <span class="pull-right">
    <%= f.submit "Send Message", class: "btn btn-success" %>
  </span>
<% end %>

app/views/messages/_message.html.erb
<% if message.sender==current_user %>
<div class="well"  align="right">
  <%= message.content %>
  <span><%= time_ago_in_words(message.created_at) %> Ago</span>
</div>
<% else %> 
<div class="well" align="left">
  <%= message.content %>
  <span><%= time_ago_in_words(message.created_at) %> Ago</span>
</div>
<% end %> 

app/views/users/index.html.erb
<head>
<style>

.titulo{
    margin-left: 60px;
}

.lista{
    margin-left: 100px;
}

</style>
</head>



<div class="titulo">
    <h3>New Chat</h3>
    <p>Select a user:</p>
</div>


<div class="lista">
    <% @users.each do |user| %>
    <div>
  
  
    
      <% if user != current_user %> 

      <%= link_to  user.name, conversations_path(id_receptor: user.id, user_id: current_user.id), method: 'post' %>
        <%= user.email %>
      <% end %>
    </div>
      <br>
<% end %>
</div>